# Generated by Django 3.2.9 on 2022-04-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_remove_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=1000, null=True),
        ),
    ]
