# Generated by Django 3.2.9 on 2022-04-11 00:45

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20220410_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='vendor',
            field=models.CharField(default='ABC', max_length=20, verbose_name=accounts.models.Vendor),
        ),
    ]
