# Generated by Django 3.2.9 on 2022-04-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_auto_20220420_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cartID',
            field=models.CharField(default='ABC', max_length=255),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Started', 'Started'), ('Abandoned', 'Abandoned'), ('Finished', 'Finished')], default='Pending', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Started', 'Started'), ('Abandoned', 'Abandoned'), ('Finished', 'Finished')], default='Started', max_length=20),
        ),
    ]
