# Generated by Django 3.2.8 on 2022-04-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
