# Generated by Django 3.2.8 on 2022-03-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_vet'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='service_information',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
