# Generated by Django 3.2.8 on 2022-04-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20220429_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet_appointment',
            name='f1',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='f2',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='f3',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='f4',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='m1',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='m2',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='m3',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='m4',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='t1',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='t2',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='t3',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='t4',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='th1',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='th2',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='th3',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='th4',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='w1',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='w2',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='w3',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='vet_appointment',
            name='w4',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
