# Generated by Django 3.2.8 on 2022-02-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220208_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='company_info',
            new_name='service_information',
        ),
        migrations.RemoveField(
            model_name='rescueservice',
            name='email',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='email',
        ),
    ]
