# Generated by Django 3.2.8 on 2022-02-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220211_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('is_approved', models.BooleanField(default=False)),
                ('experience', models.TextField(null=True)),
            ],
        ),
    ]
