# Generated by Django 3.2.8 on 2022-03-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_vet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vet',
            field=models.BooleanField(default=False),
        ),
    ]
