# Generated by Django 3.2.9 on 2022-04-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220411_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='role',
        ),
    ]
