# Generated by Django 3.2.9 on 2022-04-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_vet_appointment'),
        ('accounts', '0023_auto_20220411_0612'),
    ]

    operations = [
    ]
