# Generated by Django 3.2.9 on 2022-04-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_auto_20220412_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Started', 'Started'), ('Abanodned', 'Abandoned'), ('Finished', 'Finished')], default='Pending', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='{user.address}', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='ABC', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Started', 'Started'), ('Abanodned', 'Abandoned'), ('Finished', 'Finished')], default='Started', max_length=20),
        ),
    ]
