# Generated by Django 3.2.9 on 2022-04-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vet_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.BooleanField(default=False)),
                ('a2', models.BooleanField(default=False)),
                ('a3', models.BooleanField(default=False)),
                ('a4', models.BooleanField(default=False)),
                ('day', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vet')),
            ],
        ),
    ]
