# Generated by Django 3.2.9 on 2022-04-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_vet_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vet_appointment',
            old_name='a1',
            new_name='f1',
        ),
        migrations.RenameField(
            model_name='vet_appointment',
            old_name='a2',
            new_name='f2',
        ),
        migrations.RenameField(
            model_name='vet_appointment',
            old_name='a3',
            new_name='f3',
        ),
        migrations.RenameField(
            model_name='vet_appointment',
            old_name='a4',
            new_name='f4',
        ),
        migrations.RemoveField(
            model_name='vet_appointment',
            name='day',
        ),
        migrations.AddField(
            model_name='vet_appointment',
            name='m1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet_appointment',
            name='m2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet_appointment',
            name='m3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet_appointment',
            name='m4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet_appointment',
            name='t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet_appointment',
            name='t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet_appointment',
            name='t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet_appointment',
            name='t4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet_appointment',
            name='th1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet_appointment',
            name='th2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet_appointment',
            name='th3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet_appointment',
            name='th4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet_appointment',
            name='w1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet_appointment',
            name='w2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet_appointment',
            name='w3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vet_appointment',
            name='w4',
            field=models.BooleanField(default=False),
        ),
    ]
