# Generated by Django 3.2.9 on 2022-04-20 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220419_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet_appointment',
            name='client',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
