# Generated by Django 3.2.9 on 2022-04-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_vet_appointment_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vet_appointment',
            name='client',
        ),
    ]
